#ifndef __START_H
#define __START_H
/*
 * This is fusion file to join c++ project and main.c file generated by CubeMX
 */

// Make fusion like Arduino does
#ifdef __cplusplus
extern "C" {
#endif

void setup(void);
void loop(void);

#ifdef __cplusplus
}
#endif

#endif
